---

environment:
  run: python3 environment/training.py
  name: PongDeterministic-v4
  shape: [42, 42, 1]                    # [height, width, channels] of env's input
  max_episodes: 100000
  infinite_run: False

metrics:
  episode_reward: true
  server_latency: true
  action: true
  mu: true
  sigma2: true
  critic: true

relaax-metrics-server:
  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics: false
  log_level: INFO

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: logs/checkpoints
  --log-level: INFO

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO

algorithm:
  name: da3c

  input:
    shape: [42, 42, 1]
    history: 1
    use_convolutions: true

  output:
    continuous: false
    action_size: 6                # action size for the given environment

  hidden_sizes: [256]
  batch_size: 20                  # local loop size for one episode

  use_icm: false                  # to use ICM, set to the True
  use_lstm: true                  # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  use_gae: True                   # switcher for generalized advantage estimation
  gae_lambda: 1.00                # lambda for generalized advantage estimation

  initial_learning_rate: 1e-4
  gradients_norm_clipping: 40.    # gradients clipping global norm
  optimizer: Adam

  RMSProp:
    decay: 0.99
    epsilon: 0.1

  ICM:
    alpha: 0.1
    beta: 0.2
