algorithm:
  name: da3c

  input:
    shape: [84, 84]               # state: [height, width] or [height, width, channels]
    history: 4                    # number of consecutive states to stuck to represent an input
    use_convolutions: true

  output:
    continuous: false
    action_size: 6                # action size for the given environment

  batch_size: 5                   # local loop size for one episode
  hidden_sizes: [256]

  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  initial_learning_rate: 7e-4
  entropy_beta: 1e-2              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor

  RMSProp:
    decay: 0.99
    epsilon: 0.1
  gradient_norm_clipping: 40
