---

# This is an example of configuration to train DA3C agent with DeepMind Lab.
#
# To run this training navigate to empty directory next to relaax repo,
# open three terminals there and run:
# relaax-parameter-server --config ../relaax/config/da3c_lab_demo.yaml
# relaax-rlx-server --config ../relaax/config/da3c_lab_demo.yaml


relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: checkpoints/lab_a3c
  --log-level: WARNING

relaax-rlx-server:
  --bind: localhost:7001
  --parameter-server: localhost:7000
  --log-level: WARNING
  --log-dir: logs

algorithm:
  path: ../relaax/algorithms/da3c

  action_size: 11                 # action size for discretisize Lab's agent
  episode_len: 5                  # local loop size for one episode
  gpu: false                      # to use GPU, set to the True
  lstm: false                     # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  initial_learning_rate: 7e-4
  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
