---

# This is an example of configuration to train DA3C Continuous with gym's BipedalWalker-v2.
#
# To run this training navigate to empty directory next to relaax repo,
# open three terminals there and run:
# relaax-parameter-server --config ../relaax/config/da3c_gym_boxing.yaml
# relaax-rlx-server --config ../relaax/config/da3c_gym_boxing.yaml
# ../relaax/environments/OpenAI_Gym/main --rlx-server localhost:7001 --env Boxing-v0

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: checkpoints/boxing_a3c_gym
  --log-level: WARNING
  --metrics-dir: metrics_gym_boxing

relaax-rlx-server:
  --bind: 0.0.0.0:7001
  --parameter-server: localhost:7000
  --log-level: WARNING

algorithm:
  path: ../relaax/algorithms/da3c

  action_size: 18                 # action size for the given environment
  state_size: [84, 84]            # array of dimensions for the input observation
  history_len: 4                  # number of observations to stack in state
  episode_len: 5                  # local loop size for one episode
  gpu: false                      # to use GPU, set to the True
  lstm: true                      # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  initial_learning_rate: 7e-4
  entropy_beta: 1e-2              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
